### ISSUE TITLE
Not Working in MX9 

### ISSUE THREAD

**Issue by putladinesh** [imeidopf/mendix_SweetAlert2#3]
The module is not supported in MX9 versions.
![SweetAlert](https://user-images.githubusercontent.com/108924503/177947341-038528f3-bccb-485e-8a6d-8f1e59c60a58.PNG)

**Comment by imeidopf** [comment]
@putladinesh Have you properly referenced the javascript file in your index.html page?

**Comment by putladinesh** [comment]
> @putladinesh Have you properly referenced the javascript file in your index.html page?

Hi , 
Yes, I have referenced the java script file correctly on index.html page. 

I downloaded the module on 9.12.1. Since Mx 9 does not have an index.html file. I copied the index file from the Deployment directory and pasted it into Theme Directory. Then Followed the documentation( Placed the vendor folder in the Theme folder and referenced in the CSS and Script file in the head section of the index.html file

Attaching the Index.html file for Reference. 

![image](https://user-images.githubusercontent.com/108924503/178281598-01a40613-0093-47a3-95e9-486584a60451.png)

The same code is working fine in MX8 :)

**Comment by imeidopf** [comment]
@putladinesh What version of Mx 9 are you testing this in?

**Comment by putladinesh** [comment]
> @putladinesh What version of Mx 9 are you testing this in?

Mx version : 9.12.1

**Comment by imeidopf** [comment]
Closing this, as I am releasing an updated version with updated instruction.
